name = "Containers"
uuid = "8f51d76f-989b-4dfb-b882-e77df0ec16dd"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it> and contributors"]
version = "1.0.1"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
