name = "MixedTypesContainers"
uuid = "d538787b-fcd7-45dd-a3fb-92a4ecb31e9f"
authors = ["Andrea Pasquale <andrea.pasquale@polimi.it> and contributors"]
version = "1.0.0"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
